Rails.application.routes.draw do
  get 'menus/index'
  get 'menus/show'
  get 'menus/new'
  get 'menus/create'
  get 'menus/edit'
  get 'menus/update'
  get 'menus/destroy'
  get 'restaurants/index'
  get 'restaurants/new'
  get 'restaurants/create'
  get 'restaurants/edit'
  get 'restaurants/update'
  get 'restaurants/destroy'
  get 'category/index'
  get 'owner/new'
  get 'owner/create'
  get 'owner/show'
  get 'owner/edit'
  get 'owner/update'
  get 'owner/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
